// <auto-generated />
namespace KickyLegs.Domain.DataContext.EventMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class updatedcaffeinetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedcaffeinetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201503082308586_updated caffeine time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
